.TH UTP_INDEX 5 "27 January 2003" "UTP Revival v1.0"
.SH NAME
utp_index \- format of index entries
.SH DESCRIPTION
This is a derivitive of the scripts described in
.IR "Tools for Printing Indexes" ,
CSTR #128
(Bentley & Kernighan,
http://netlib.bell-labs.com/cm/cs/cstr/128.ps.gz).
An index consist of entries specified by the
.B \&.ix
macro.
The macro writes its arguments,
followed by the current page number,
to standard error
(which must be captured for further processing).
A ``long pipeline of short
.I awk
programs'' processes the entries and formats
the index as
.I troff
markup.
.SS "Highlighting"
.P
In addition to actual index data,
entries may also contain simple markup:
.TP
.BI [ text ]
formats the text between
square brackets in Courier (or constant width font).
.TP
.BI { text }
formats the text between curly brackets in italic.
.SS "Hierarchical Entries"
.P
The index supports a two-level hierarchy.
The entries:
.P
.RS
\&.ix command, troff
.br
\&.ix command, nroff
.RE
.P
are formatted as:
.P
.RS
command
.br
\0\0\0nroff  6
.br
\0\0\0troff  4
.RE
.SS "Rotated Entries"
.P
By default, the indexing scripts rotate entries so that
the entry:
.P
.RS
\&.ix formatting text
.RE
.P
generates two entries:
.P
.RS
\&formatting text  3
.br
\&text, formatting  3\fP
.RE
.P
To prevent a word from being rotated to the
beginning on an entry, replace the space between
words with a tilde (~), such as:
.P
.RS
\&.ix formatting~text
.RE
.SS "Marking Page Ranges"
Certain index entries use a page range
to indicate an extended discussion of the
topic:
.P
.RS
\&formatting text  3-12
.RE
.P
Use the
.B %begin
and
.B %end
keywords at the beginning and end of the
section to set up a page range:
.P
.RS
\&.ix %begin formatting text
.br
.I "intervening text"
.br
\&.ix %end formatting text
.RE
.SS "Controlling the Sort Order"
Entries with leading punctuation or numbers
get sorted to the beginning of the index
unless you add the
.B %key
command to the end of an entry:
.P
.RS
\&.ix <HTML> tag %key HTML tag
.br
\&.ix 50 ways to leave %key fifty ways to leave
.RE
.SH FILES
CSTR #128 describes most of the files.
The following are scripts added since the original,
or are of further interest:
.TP
hierarchy
Creates a hierarchical index from a sorted list.
.TP
see.prep
Reads the file
.B see.terms
and creates appropriate ``see'' and ``see also''
index entries to sort into the rest of the index.
The entries in the
.B see.terms
file should look like:
.P
.RS
foo (tab) bar
.br
baz (tab) quux %also
.RE
.P
The first example generates a ``see'' entry,
and the second example a ``see also'' entry.
.SH HISTORY
The original index package was created and
used for building the index for the books
.I "Unix Programming Environment"
and
.IR "Programming Pearls" .
The package was further updated (adding support
for hierarchical entries) for use with the book
.I "A Modeling Language for Mathematical Programming"
(http://www.ampl.com/).
Jon Snader and Larry Kollar made a few additional
tweaks for printing the revived
.IR "Unix Text Processing" .
.P
A side note: in CSTR #128, the authors tell us
that their VAX 11/750 took 234 seconds (roughly
six minutes) to format an index with 1100 input
lines.
The test input generated from
.I "Unix Text Processing"
is about 2200 input lines and takes
slightly less than five seconds to build
using a four year old G3/266 running MacOS X.
As Jon Snader put it,
``It now takes more computer power to run Mozilla
than it did to get us to the moon.''
